SectionDevice."Speaker" {
	Comment "Speaker playback"

	ConflictingDevice [
		"Headphones"
		"Earpiece"
	]

	EnableSequence [
		cset "name='RX1 MIX1 INP1' RX1"
		cset "name='RX1 MIX1 INP2' RX2"
		cset "name='HPHL' 1"
		## gain to  0dB
		cset "name='RX1 Digital Volume' 84"
		cset "name='Speaker Switch' 1"
	]

	DisableSequence [
		cset "name='Speaker Switch' 0"
		cset "name='RX1 Digital Volume' 0"
		cset "name='HPHL' 0"
		cset "name='RX1 MIX1 INP1' ZERO"
		cset "name='RX1 MIX1 INP2' ZERO"
	]

	Value {
		PlaybackPCM "${var:WcdPlaybackPCM}"
		PlaybackChannels 2
		PlaybackPriority 200
	}
}
